Algoritmo "SOMA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Solicita e soma dois valores.
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 21/05/2026

Var
// Seção de Declarações das variáveis 
v1, v2: inteiro
soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval (" --------------- ")
Escreval (" SOMA DE VALORES ")
Escreval (" --------------- ")
Escreval ("")

         Escreva (" INSIRA O VALOR 01: ")
            Leia (v1)
            
         Escreva (" INSIRA O VALOR 02  ")
            Leia (v2)
            
            soma <- (v1 + v2)
         
         Escreval ("")
         Escreval (" ---------------------------- ")
         Escreval (" RESULTADO CALCULADO " , soma)
         Escreval (" ---------------------------- ")
         


Fimalgoritmo