Algoritmo "Aula 02 - Ola mundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Código "Olá Mundo" com variaveis.
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 21/05/2026


Var
// Seção de Declarações das variáveis 
msg: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval (" -------------------- ")
Escreval (" Aula 02 - Ola Mundo! ")
Escreval (" -------------------- ")
Escreval ("")

         msg <- (" Olá mundo! Me livrei da maldicao! ")
         
         Escreval (msg)


Fimalgoritmo