Algoritmo "Aula 02 - Ola mundo."
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Código simples, sem variáveis.
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 21/05/2026


Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval (" -------------------- ")
Escreval (" AULA 02 - OLÁ MUNDO! ")
Escreval (" -------------------- ")
Escreval ("")

         Escreval (" Olá mundo! ")
         Escreval (" Me livrei da maldição. ")


Fimalgoritmo