Algoritmo "INSERIR NOME"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Solicita o nome do user e atribui em uma variavel
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 21/05/2026

Var
// Seção de Declarações das variáveis 
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval (" ---------------------- ")
Escreval (" INSERIR O NOME DE USER ")
Escreval (" ---------------------- ")
Escreval ("")

         Escreva (" INSERIR O NOME: ")
         Leia (nome)
         
         Escreval (" NOME CADASTRADO COM SUCESSO! ")
         Escreval (" ... ")
         Escreval (" .. ")
         
         Escreval (" ------------------------------ ")
         Escreval (" SEJA BEM VINDO(A): " , nome)
         Escreval (" ------------------------------ ")

Fimalgoritmo