Algoritmo "CALCULO DA MEDIA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Calcula a Media de dois valores
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 21/05/2026

Var
// Seção de Declarações das variáveis 
v1, v2, media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval (" ---------------- ")
Escreval (" CALCULA DE MEDIA ")
Escreval (" ---------------- ")
Escreval ("")

         Escreva (" DIGITE O 1º VALOR: ")
            Leia (v1)
            
         Escreva (" DIGITE O 2º VALOR: ")
            Leia (v2)
            

             media <- ((v1 + v2) / 2)
             
Escreval ("")
Escreval (" ----------------------- ")
Escreval (" MEDIA CALCULADA: " , media)
Escreval (" ----------------------- ")



Fimalgoritmo